# Problem 1 

In [2]:
# 1 - numpy kütüphanesini import edin
import numpy as np

# 2 - 5 elemanlı bir numpy array oluşturun
a = np.array([1,52,95,2,88])

# 3 - Oluşturduğunuz arrayi küçükten büyüğe sıralayın.
print(a)
print(np.sort(a))

[ 1 52 95  2 88]
[ 1  2 52 88 95]


# Problem 2

In [6]:

# 1- (10,15,30,45,60) değerlerine sahip numpy dizisi oluşturunuz.
result = np.array([10,15,30,45,60])
print("1.Soru" , result)
# 2- (5-15) arasındaki sayılarla numpy dizisi oluşturunuz.
result = np.arange(5,15)
print("2.Soru" , result)
# 3- (50-100) arasında 5'er 5'er artarak numpy dizisi oluşturunuz.
result = np.arange(50,100,5)
print("3.Soru" , result)
# 4- 10 elemanlı sıfırlardan oluşan bir dizi oluşturunuz.
result = np.zeros(10)
print("4.Soru" , result)
# 5- 10 elemanlı birlerden oluşan bir dizi oluşturunuz.
result = np.ones(10)
print("5.Soru" , result)
# 6- (0-100) arasında eşit aralıklı 5 sayı üretin.
result = np.linspace(0,100,5)
print("6.Soru" , result)
# 7- (10-30) arasında rastgele 5 tane tamsayı üretin.
result= np.random.randint(10,30,size=5)
print("7.Soru" , result)
# 8- [-1 ile 1] arasında 10 adet sayı üretin.
result = np.random.uniform(-1,1,size=10)
print("8.Soru" , result)
# 9- (3x5) boyutlarında (10-50) arasında rastgele bir matris oluşturunuz.
result = np.random.randint(10,50,size=(3,5))
print("9.Soru" , result)
# 10- Üretilen matrisin satır ve sütun sayıları toplamlarını hesaplayınız ?
sum1 = result.sum(axis = 1)
sum2 = result.sum(axis = 0)
print("10.Soru 1-)", sum1)
print("10.Soru 2-)" , sum2)
# 11- Üretilen matrisin en büyük, en küçük ve ortalaması nedir ?
print("11.Soru",
result.min(),
result.max(),
result.mean())
# 12- Üretilen matrisin en büyük değerinin indeksi kaçtır ?
print("12.Soru" , result.argmax())
# 13- (10-20) arasındaki sayıları içeren dizinin ilk 3 elemanını seçiniz.
array = np.arange(10,20)
print("13.Soru", array , "İlk Üç eleman=" , array[:3])
# 14- Üretilen dizinin elemanlarını tersten yazdırın.
print("14.Soru" , array[::-1])
# 15- Üretilen matrisin ilk satırını seçiniz.
print("15.Soru ", result[0])
# 16- Üretilen matrisin 2.satır 3.sütundaki elemanı hangisidir ?
print("16.Soru ", result[1,2])
# 17- Üretilen matrisin tüm satırlardaki ilk elemanı seçiniz.
print("17.Soru ", result[:,0])
# 18- Üretilen matrisin her bir elemanının karesini alınız.
print("18.Soru " , array**2)
print("18.Soru 2 ", np.power(array,2))
# 19- Üretilen matris elemanlarının hangisi pozitif çift sayıdır ? Aralığı (-50,+50) arasında yapınız.
son_soru = np.arange(-50,50)
print("19.Soru",
son_soru[(son_soru % 2 ==0) & (son_soru >0)])

1.Soru [10 15 30 45 60]
2.Soru [ 5  6  7  8  9 10 11 12 13 14]
3.Soru [50 55 60 65 70 75 80 85 90 95]
4.Soru [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
5.Soru [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
6.Soru [  0.  25.  50.  75. 100.]
7.Soru [25 15 10 13 22]
8.Soru [ 0.43249777 -0.23733961  0.89273818 -0.85233531  0.12388364 -0.98120922
 -0.60013537  0.08355684 -0.6445143  -0.48813257]
9.Soru [[29 21 39 44 30]
 [32 47 16 36 13]
 [24 28 47 15 21]]
10.Soru 1-) [163 144 135]
10.Soru 2-) [ 85  96 102  95  64]
11.Soru 13 47 29.466666666666665
12.Soru 6
13.Soru [10 11 12 13 14 15 16 17 18 19] İlk Üç eleman= [10 11 12]
14.Soru [19 18 17 16 15 14 13 12 11 10]
15.Soru  [29 21 39 44 30]
16.Soru  16
17.Soru  [29 32 24]
18.Soru  [100 121 144 169 196 225 256 289 324 361]
18.Soru 2  [100 121 144 169 196 225 256 289 324 361]
19.Soru [ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]
