# Problem 1

In [9]:
# 1 - numpy kütüphanesini import edin
import numpy as np

# 2 - 0 ile 10 arasında 5 sayıdan oluşan matris üretin
b = np.random.randint(0,10,size=5)
print(b)

# 3 - matris'in boyutunu öğrenin
print(b.shape)
# 4 - matris'i yeniden boyutlandırın
c = b.reshape(5,1)
print(c)

# 5 - matris'in boyut sayısını öğrenin
print(b.ndim)
print(c.ndim)

[2 2 9 1 5]
(5,)
[[2]
 [2]
 [9]
 [1]
 [5]]
1
2


# Problem 2

In [28]:
# 1 - 0 ile 10 arasında bulunan tek sayılardan oluşan matris üretin
a = np.arange(1,11,2)
print(a)

# 2 - Oluşturduğunuz matrisi parçalayın
a,b,c = (np.split(a, [1,3])) 
print(a)
print(b)
print(c)
# 3 - Parçalanmış matrisleri birleştirin
print(np.concatenate([a,b,c]))


[1 3 5 7 9]
[1]
[3 5]
[7 9]
[1 3 5 7 9]


# Problem 3

In [35]:
# 1 - 5 ile 100 arasında ikişer ikişer atlayarak rastgele 10 sayıdan oluşan matris üretin
a = np.random.randint(5,100,size=(5,2))
print(a)
# 2 - matris'in özelliklerini inceleyin
print(a.shape)
print(a.ndim)
print(a.size)
print(a.dtype)

[[43 81]
 [95 12]
 [73 31]
 [88 83]
 [38 69]]
(5, 2)
2
10
int32
