# Numpy
- Numpy sayısal işlemleri hızlı yapmak için C dili ile yazılmış bir Python kütüphanesidir.
- Veri analizinde kullanılır.
- Bilgisayar kurmak için ```pip insall numpy``` komutu ile kurulabilir.
- Bilimsel hesaplamalar için kullanılır.
- Arraylar(diziler) / çok boyutlu arrayler(matrisler) üzerinde yüksek performanslı işlemler yapılabilir.
- Temelleri 1995 yılında atıldı. Ama nihai olarak 2005 yılında Travis Oliphant tarafından hayata geçmiştir.
- Listelere benzerdir. Fakat verimli veri saklama ve vektör işlemleri için Numpy kullanılır.

In [ ]:
pip install numpy

### Dizi(array) ve liste farkları:

Python'da, dizi (array) ve liste (list) her ikisi de birden fazla öğenin saklanması için kullanılan veri yapılarıdır. Ancak, diziler ve listeler arasında bazı farklılıklar vardır:

1.) Veri tipi: Diziler, homojen bir veri tipine sahip öğeleri tutmak için kullanılırken, listeler heterojen veri tipleri için kullanılabilir. Yani, bir dizi yalnızca tamsayıları veya yalnızca ondalık sayıları tutabilirken, bir listede hem tamsayılar hem de ondalık sayılar yer alabilir.

2.) Bellek yönetimi: Diziler bellek yönetimi açısından daha verimlidir. Listeler, elemanları farklı bellek adreslerinde saklar ve bir listenin her elemanı, bellekte farklı bir konumda depolanırken, diziler bellekte ardışık bir alanda saklanır.

3.) Boyut: Diziler tek boyutlu veya çok boyutlu olabilirken, listeler sadece tek boyutludur.

4.) İşlemler: Diziler, matematiksel işlemleri yapmak için uygun bir şekilde tasarlanmıştır. Bu nedenle, NumPy ve diğer kütüphaneler dizileri kullanarak veri işleme işlemlerini gerçekleştirmek için kullanılır. Listeler ise genellikle öğelerin eklenmesi, çıkarılması, sıralanması, aranması gibi işlemler için kullanılır.

Özetle, diziler ve listeler arasındaki temel fark, veri tipi, bellek yönetimi, boyut ve işlemlerdir. Diziler homojen veriler için daha uygundurken, listeler heterojen veriler için daha uygundur ve her ikisi de farklı veri işleme ihtiyaçlarına yöneliktir.

In [13]:
my_list = ([1, 2, 3], [4, 5, 6])
print(my_list)

([1, 2, 3], [4, 5, 6])


In [12]:

my_array = np.array([[1, 2, 3], [4, 5, 6]])
print(my_array)


[[1 2 3]
 [4 5 6]]


In [4]:
# bir dizi (array) oluşturma
my_array = np.array([1, 2, 3, 4, 5])
print("Dizi: ", my_array)
print("Dizinin boyutu: ", my_array.shape)
print("Dizinin veri tipi: ", my_array.dtype)

# bir liste (list) oluşturma
my_list = [1, "iki", 3.0, "dört", 5]
print("Liste: ", my_list)
print("Listenin boyutu: ", len(my_list))

# dizi ile matematiksel işlem yapma
my_array_squared = my_array ** 2
print("Dizinin karesi: ", my_array_squared)

# listenin öğelerini ekleme ve silme
my_list.append("altı")
print("Listeye 'altı' eklendi: ", my_list)

my_list.remove("iki")
print("Listeden 'iki' çıkarıldı: ", my_list)


Dizi:  [1 2 3 4 5]
Dizinin boyutu:  (5,)
Dizinin veri tipi:  int32
Liste:  [1, 'iki', 3.0, 'dört', 5]
Listenin boyutu:  5
Dizinin karesi:  [ 1  4  9 16 25]
Listeye 'altı' eklendi:  [1, 'iki', 3.0, 'dört', 5, 'altı']
Listeden 'iki' çıkarıldı:  [1, 3.0, 'dört', 5, 'altı']


Bu örnekte, bir dizi ve bir liste oluşturduk. Dizinin elemanları tam sayı, liste ise hem tam sayı hem de string ifadeler içeriyor. Dizinin boyutunu shape özelliği ile kontrol ederken, listenin boyutunu len fonksiyonu ile kontrol ettik. Dizi için matematiksel bir işlem yaparken, listenin elemanlarını ekleyip ve çıkardık. Bu örnek, dizilerin matematiksel işlemler için daha uygun olduğunu ve listelerin veri ekleme ve çıkarma işlemleri için daha uygun olduğunu göstermektedir.

----

## Array ve matris farkı nedir?

Python'da bir dizi, tek boyutlu bir veri yapısıdır. Bu dizi, aynı veri türünden elemanları içerir ve indeksleme yöntemi kullanılarak erişilebilir.

Bir matris ise, iki boyutlu bir veri yapısıdır ve satır ve sütunlardan oluşur. Matrisler, aynı veri türünden elemanları içerir ve bir öğenin konumu, satır ve sütun indeksleri kullanılarak belirlenir. Matrisler, bir dizi gibi düzgün bir şekilde düzenlenmiş bir veri yapısıdır ve matematiksel işlemler için kullanılabilirler.

Python'da, bir dizi oluşturmak için array modülünü kullanabilirsiniz, ancak bu sadece tek boyutlu bir dizi oluşturur. Matrisler için ise, numpy modülü kullanılabilir. numpy modülü, matrislerin yanı sıra çok boyutlu diziler için de kullanılabilir.

Python'da, bir dizi (array) veya matris (matrix) kullanarak çok boyutlu verileri temsil edebilirsiniz.

Bir dizi, aynı türdeki öğelerin sıralı bir koleksiyonudur. Örneğin, bir dizi içinde tam sayılar, ondalık sayılar veya karakterler gibi veri tipleri yer alabilir. NumPy gibi kütüphaneler, Python'da dizileri işlemek için kullanılabilir.

Bir matris, iki boyutlu bir dizi olarak düşünülebilir ve bu nedenle aynı türdeki öğelerin düzenli bir şekilde yer aldığı bir koleksiyondur. Bir matris, satırlar ve sütunlar olmak üzere iki boyutlu bir indekslemeye sahiptir ve bu şekilde elemanlarına erişilebilir. Örneğin, bir matris içinde tamsayılar, ondalık sayılar veya karmaşık sayılar gibi veri tipleri yer alabilir. NumPy kütüphanesi, Python'da matrisleri işlemek için kullanılabilir.

Özetle, dizi tek boyutlu bir veri koleksiyonunu, matris ise iki boyutlu bir veri koleksiyonunu ifade eder.

Bir örnek ile açıklamak gerekirse:

In [23]:
import numpy as np

# bir array (dizi) oluşturma
my_array = np.array([1, 2, 3, 4, 5])
print("Array: ", my_array)
print("Array boyutu: ", my_array.shape)

# bir matris (matrix) oluşturma
my_matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Matris: ")
print(my_matrix)
print("Matris boyutu: ", my_matrix.shape)


Array:  [1 2 3 4 5]
Array boyutu:  (5,)
Matris: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Matris boyutu:  (3, 3)


## Matrisleri İsimlendirme


![Image](https://cdn.programiz.com/sites/tutorial2program/files/matrix.jpg)

![Image](https://www.guru99.com/images/2/062620_0641_PythonMatri1.png)

``
*Önce row(satır) sayısı,sonra column(sütun)sayısı yazılır.*
``

Python'da, birden fazla boyutu olan dizilere (arrays) "çok boyutlu diziler" denir. NumPy kütüphanesi, Python'da çok boyutlu dizileri kullanmak için yaygın bir araçtır.

Örneğin, 2x3 boyutlu bir dizi(array) şu şekilde oluşturulabilir:

In [3]:

my_array = np.array([[1, 2, 3], [4, 5, 6]])
print(my_array)


[[1 2 3]
 [4 5 6]]


In [11]:
my_list = ([1, 2, 3], [4, 5, 6])
print(my_list)

([1, 2, 3], [4, 5, 6])


Bu örnekte, np.array() fonksiyonu ile bir 2x3 ``(Önce row(satır),daha sonra column(sütun)sayısı yazılır.)`` boyutlu bir dizi oluşturuldu. İç içe iki liste kullanarak her satırın elemanlarını belirttik. Dizinin her bir öğesi, [satır, sütun] şeklinde bir indeksleme kullanılarak erişilebilir. Örneğin, my_array[0, 1] ifadesi, ilk satırın ikinci sütunundaki öğeye erişecektir ve 2 sonucunu verecektir.

# Neden Numpy?

In [18]:
#KLasik Yöntem
a = [1,2,3,4]
b = [2,3,4,5]
c = 0
ab = []
for i in range(0, len(a)):
    print(i,". dolaşma")
    c+=1
    ab.append(a[i] * b[i])
print(c,"kez dolaştım.")
print(ab)

0 . dolaşma
1 . dolaşma
2 . dolaşma
3 . dolaşma
4 kez dolaştım.
[2, 6, 12, 20]


In [4]:
#Numpy Metodu
import numpy as np #np olarak çağırabileyim.Kısaltma olarak np koydum.
a = np.array([1,2,3,4]) #Numpy'da array oluştururken np.array yöntemi kullanılır.
print(a)
b = np.array([2,3,4,5])
print(b)
print(a*b)

[1 2 3 4]
[2 3 4 5]
[ 2  6 12 20]


## Numpy Fonksiyonları

.reshape() : arraylerin veya matrislerin boyutunu değiştirir.

In [25]:
x = np.array([1,2,3,4,5,6,7,8,9]) # 1 boyutlu bir array'dir. Boyutu 9'dur, yani içinde dokuz eleman bulunur.
#x bir sütun matrisi (9x1) değil, tek boyutlu bir dizi veya vektördür (1x9)(önce satır sonra sütun)
# Ancak biz 1x9 demek yerine böyle arraylere 9'a 0'lık(9, ) array deriz.
print(x)
multi = x.reshape(3,3) #multi ise 2 boyutlu bir matristir.(çok boyutlu bir arraydir.)
#3x3'lük(3,3) bir matristir.(3satır,3 sütun)
print(multi)
#Aslında biz burda bir arrayı matrise çevirdik.

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


.shape : arraylerin veya matrislerin boyutlarını verir.(...x...) şeklinde    

In [29]:
print(x.shape)

(9,)


In [27]:
print(multi.shape)

(3, 3)


ndim : Arraylerin veya Matrislerin  boyut sayısını verir.(Kaç boyutlu olduğu söyler.)  

In [20]:
print(x.ndim) #1 boyutludur.

1


In [21]:
print(multi.ndim) #2 boyutludur.
# 2 boyutlu matris
#       veya
# 2 boyutlu array
# diyebiliriz.Her ikisi de aynı anlama gelir.

2


# Birleştirme (Concatenation)
- .concatenate() fonksiyonu ile birleştirme yapabiliriz.Örneğin elimizde 2 tane numpy arrayi olsun,biz bu 2 arrayi birleştirmek için kullanırız.

In [33]:
x = np.array([1,2,3,4,5])
print(x)
y = np.array([6,7,8,9,10])
print(y) # Bunu ayrık yazmasının sebebi içinde 2 basamaklı bir sayı bulunmasıdır.
print(np.concatenate([x, y]))

[1 2 3 4 5]
[ 6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]


---

- Bunu ayrık yazmasının sebebi içinde 2 basamaklı bir sayı bulunmasıdır.

In [36]:
y = np.array([6,7,8,9])
print(y)
y = np.array([6,7,8,9,10])
print(y)

[6 7 8 9]
[ 6  7  8  9 10]
[11 12 13 14]


-------

-----

In [60]:
z = np.array([11,12,13,14,15])
print(z) #Bir boyutlu array.

[11 12 13 14 15]


In [61]:
z = np.array([[11,12,13,14,15]])
print(z) #İki boyutlu array.

[[11 12 13 14 15]]


In [63]:
a = np.array([1,2,3], [4,5,6])
print(a)
#Yani böyle yaparsan hata alırsın.Sen bana 2 boyutlu bir şey verdin
#Ama tek köşeli parantez([]) kullanarak bunun tek boyutlu olduğunu söylüyorsun der.

TypeError: Field elements must be 2- or 3-tuples, got '4'

In [24]:
a = np.array([[1,2,3], [4,5,6]])
print(a) #Sorunu iki tane [[]] kullanarak çözdük.

[[1 2 3]
 [4 5 6]]


-----

In [2]:
import numpy as np

In [58]:
z = np.array([11,12,13,14,15])
print(np.concatenate([x, y, z]))

[ 1  2  3  4  5 11 12 13 14 11 12 13 14 15]


In [3]:
a = np.array([[1,2,3], [4,5,6]])
print(a)


[[1 2 3]
 [4 5 6]]


In [4]:
b = np.array([[7,8,9]])
print(b)

[[7 8 9]]


In [5]:
print(np.concatenate([a,b])) 


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
print(np.concatenate([a,a])) 

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]


axis = 0 ise satır bazında birleştirme yapar.(Dikey olarak)

axis = 1 ise sütun bazında birleştirme yapar.(Yatay olarak)

In [21]:
c = np.array([[7,8,9], [10,11,12]])
print(c)

[[ 7  8  9]
 [10 11 12]]


In [10]:
print(np.concatenate([a,c], axis=0))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


```
EVET DİKEY VE YATAYLAR DOĞRU YAZILDI.TERS MANTIK VAR.
** AXİS = 0 DEDİĞİNDE:
1.DİZİ İÇİN:
[0][0]   [0][1]
[1][0]   [1][1]
[2][0]   [2][1]
....
....
SATIR BİTENE KADAR
2.DİZİ İÇİN:
[0][0]   [0][1]
[1][0]   [1][1]
[2][0]   [2][1]
....
....
SATIR BİTENE KADAR
** AXİS = 1 DEDİĞİNDE:
1.DİZİ İÇİN:                                     2.DİZİ İÇİN:
[0][0] [0][1] [0][2]...SÜTUN SAYISI BİTENE DEK.. [0][0] [0][1] [0][2]
[0][0] [0][1] [0][2]...SÜTUN SAYISI BİTENE DEK.. [0][0] [0][1] [0][2]



```

In [ ]:
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]

In [17]:
print(np.concatenate([a,a], axis=0))

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]


In [19]:
print(a)
print("-----------")
print(c)

[[1 2 3]
 [4 5 6]]
-----------
[[ 7  8  9]
 [10 11 12]]


In [18]:
print(np.concatenate([a,c], axis=1))

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [12]:
print(np.concatenate([a,a], axis=1))

[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


# Array Ayırma (Splitting)

## .split() fonksiyonu ile array ayırma yapabiliriz.

In [55]:
m = np.array([1,2,3,4,5,6,7,8,9])
print(m)
print(m[0])
print(m[1])
print(m[2])
print(m[3])
print(m[4])
print(m[5])
print(m[6])
print(m[7])
print(m[8])

[1 2 3 4 5 6 7 8 9]
1
2
3
4
5
6
7
8
9


In [50]:
print(np.split(m, [3,5])) #3.elemandan(indexten) 5.elemana(indexe) kadar.(5 dahil değil.)

[array([1, 2, 3]), array([4, 5]), array([6, 7, 8, 9])]


In [23]:
n = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
print(np.split(n, [3,5]))

[array([1, 2, 3]), array([4, 5]), array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15])]


In [26]:
print(np.split(n, [1,5]))

[array([1]), array([2, 3, 4, 5]), array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15])]


In [30]:
print(np.split(n, [10,12]))

[array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]), array([11, 12]), array([13, 14, 15])]


In [3]:
print(np.split(np.arange(10),[3,5]))

[array([0, 1, 2]), array([3, 4]), array([5, 6, 7, 8, 9])]


In [56]:
a,b,c = np.split(m, [3,5])
print(a,b,c)
print(a)
print(b)
print(c)

[1 2 3] [4 5] [6 7 8 9]
[1 2 3]
[4 5]
[6 7 8 9]


In [31]:
a,b,c = np.split(n, [10,12])
print(a,b,c)
print(a)
print(b)
print(c)

[ 1  2  3  4  5  6  7  8  9 10] [11 12] [13 14 15]
[ 1  2  3  4  5  6  7  8  9 10]
[11 12]
[13 14 15]


## arange() fonksiyonu  belirli bir aralıktaki sayıları içeren bir dizi oluşturmak için kullanılan bir fonksiyondur.
* Fonksiyonun genel kullanımı şu şekildedir:
* ``numpy.arange([start,] stop[, step,][, dtype=None])``
* start (opsiyonel): Diziye dahil edilecek ilk sayı. Varsayılan olarak 0'dır.
* stop: Diziye dahil edilmeyecek son sayı.
* step (opsiyonel): Sayılar arasındaki artışın miktarı. Varsayılan olarak 1'dir.
* dtype (opsiyonel): Oluşturulan dizinin veri tipi. Varsayılan olarak None olarak ayarlanır, ancak belirtilirse, oluşturulan dizi bu veri türünde olacaktır.
Örnek kullanımı:



In [32]:
# 0'dan 10'a kadar sayılar içeren bir dizi oluştur
arr1 = np.arange(10)
print(arr1)   # [0 1 2 3 4 5 6 7 8 9]
# 1'den 9'a kadar sayılar içeren bir dizi oluştur (1 dahil, 10 hariç)
arr2 = np.arange(1, 10)
print(arr2)   # [1 2 3 4 5 6 7 8 9]
# 0'dan 1'e kadar 0.1 artarak sayılar içeren bir dizi oluştur
arr3 = np.arange(0, 1, 0.1)
print(arr3)   # [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


[0 1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


Biz bu işlemi listelerde:

In [34]:
liste = []
for i in range(0,10):
    liste.append(i)
print(liste)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


şeklinde yapıyorduk.

In [46]:
n = np.arange(16)
print(n)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [8]:
n = np.arange(16).reshape(4,4) #4x4 olacak şekilde boyutunu değiştir.
print(n)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [48]:
print(n[0]) #0.satırı yazdır.
print(n[1]) #1.satırı yazdır.
print(n[2]) #2.satırı yazdır.
print(n[3]) #3.satırı yazdır.


[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]


In [49]:
print(n[0][1]) #0.satırın 1.indexini yazdır.
print(n[1][2]) #1.satırın 2.indexini yazdır.
print(n[2][3]) #2.satırın 3.indexini yazdır.
print(n[3][3]) #3.satırın 3.indexini yazdır.

1
6
11
15


In [9]:
np.split(n, [1]) #(n, [0,1]) aynı şey. 

[array([[0, 1, 2, 3]]),
 array([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

## vsplit() bir NumPy dizisini yatay olarak(satır bazında) bölerek birden fazla alt dizilere ayırır. Dizi, satırlar boyunca bölünür.
* Fonksiyonun kullanımı şu şekildedir:
* ``numpy.vsplit(array, indices_or_sections)``
* array: Bölünecek NumPy dizisidir,
* indices_or_sections: Dizideki satır sayısını kaç parçaya ayırayım(kaç alt dizeye çevireyim ?)(alt dizilerin sayısı veya bölmelerin indeksleridir.)
- Örnek olarak, 6 satır ve 4 sütundan oluşan bir NumPy dizisi alalım:

In [48]:
arr = np.arange(24).reshape((6, 4))
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


Bu diziyi, 3 parçaya ayırmak için numpy.vsplit() kullanabiliriz:

In [78]:
pieces = np.vsplit(arr, 3)
print(pieces)

[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]]), array([[16, 17, 18, 19],
       [20, 21, 22, 23]])]


Burada, pieces değişkeni, 3 adet NumPy dizi objesi içeren bir listeye atanmıştır. Bu objeler, orijinal dizinin satırlarının yatay olarak eşit bölünmüş halidir.

<img src="Vsplit.jpg" alt="görsel yorumu"> 

* BİZ 3 PARÇAYA BÖLMESİNİ SÖYLEMİŞTİK.O HALDE:
* ``*6 SATIRI 3 E BÖLECEĞİM.6/3=2 VE HER PARÇA 2 SATIRDAN OLUŞACAK.*``
* ``1.SATIR = 1.PARÇA(2 SATIRDAN OLUŞUYOR.)``
* ``2.SATIR = 2.PARÇA(2 SATIRDAN OLUŞUYOR.)``
* ``3.SATIR = 3.PARÇA(2 SATIRDAN OLUŞUYOR.)``
Gibi düşünebilirsin.

In [50]:
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [62]:
pieces = np.vsplit(arr, 4)
# Hata aldık çünkü 6 satırlık bir dizi 4 satıra tam olarak bölünmez(6/4 = 1.5) 
#Her parça 1.5 satırdan oluşamaz diyor.

ValueError: array split does not result in an equal division

In [90]:
pieces = np.vsplit(arr, 6) #6 eşit parçaya böldüm ve her parçada 6/6 = 1'den 1 satırdan oluştu.
print(pieces)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]]), array([[12, 13, 14, 15]]), array([[16, 17, 18, 19]]), array([[20, 21, 22, 23]])]


In [63]:
n = np.arange(16).reshape(4,4)
print(n)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [80]:
np.vsplit(n, [2]) #4 Satırlık arrayi 2 eşit parçaya böl.
#O Halde 4/2 = 2 den her parça da 2 satırdan oluşsun. 

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

## hsplit() fonksiyonu, bir NumPy dizisini dikey olarak bölerek birden fazla alt dizilere ayırır. Dizi, sütunlar boyunca bölünür.
* numpy.hsplit() fonksiyonu aşağıdaki şekilde kullanılır:
* ``numpy.hsplit(array, indices_or_sections)``
* array :  bölünecek NumPy dizisidir, 
* indices_or_sections :Dizideki sütun sayısını kaç parçaya ayırayım(kaç alt dizeye çevireyim ?)(alt dizilerin sayısı veya bölmelerin indeksleridir.)

Örnek olarak, 6 satır ve 4 sütundan oluşan bir NumPy dizisi alalım:

In [92]:
arr = np.arange(24).reshape((6, 4))
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


Bu diziyi, 2 parçaya ayırmak için numpy.hsplit() kullanabiliriz:

In [99]:
pieces = np.hsplit(arr, 2)
print(pieces)

[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13],
       [16, 17],
       [20, 21]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15],
       [18, 19],
       [22, 23]])]


<img src="Hsplit.jpg" alt="görsel yorumu"> 

*Toplamda 2 PARÇAYA böl.
* ``1.SÜTUN = 1.PARÇA``
* ``2.SÜTUN = 2.PARÇA``
* Gibi düşünebilirsin.

In [100]:
pieces = np.hsplit(arr, 4)
print(pieces)

[array([[ 0],
       [ 4],
       [ 8],
       [12],
       [16],
       [20]]), array([[ 1],
       [ 5],
       [ 9],
       [13],
       [17],
       [21]]), array([[ 2],
       [ 6],
       [10],
       [14],
       [18],
       [22]]), array([[ 3],
       [ 7],
       [11],
       [15],
       [19],
       [23]])]


<img src="Hsplit 2.jpg" alt="görsel yorumu"> 

In [102]:
n = np.arange(16).reshape(4,4)
print(n)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [105]:
np.hsplit(n, [2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [106]:
a,b = np.hsplit(n, [2])
print(a)
print("<------------->")
print(b)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
<------------->
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


## np.zeros()
- 0'lardan oluşan bir numpy dizisi oluşturulması için kullanılır.

In [4]:
zero = np.zeros(10)
print(zero)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


## np.ones()
- 1'lerden oluşan bir numpy dizisi oluşturulması için kullanılır.

In [5]:
one = np.ones(10)
print(one)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


## np.linspace()
- Belli bir aralıkta sayıları oluşturmak için kullanılır.
- np.linspace(başlangıç, bitiş, bölünecek aralık)

In [11]:
lins = np.linspace(0, 100, 5) #Verdiğin aralığı verdiğin sayıya bölüyor.
print(lins)
#0,100 aralığımı 5 parçaya bölerek yazdı.

[  0.  25.  50.  75. 100.]


In [12]:
np.arange(0,101,5) #Verdiğin sayı kadar atlıyor. 

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100])

In [13]:
result = np.random.randint(0, 10,3) #0 ile 10 arasında rastgele 3 sayı üret.
print(result)

[5 6 5]


In [14]:
result = np.random.arange(0,10,2) #Böyle bir özellik yok. 

AttributeError: module 'numpy.random' has no attribute 'arange'

In [16]:
np.random.randint(2,22,5) #2 ile 22 arasında rastgele 5 sayı üret.Ve np kullandığım için bunu bir arraye ata. 

array([ 7,  9,  7, 17, 13])

Eğer numpy kullanmasaydım random modülünü çağırmak zorundaydım.Çünkü random modülü numpy'ın içerisinde özelleştirilmiş bir biçimde kullanılır.

In [17]:
random.randint(0,100)

NameError: name 'random' is not defined

In [19]:
import random

In [28]:
random.randint(0,100,2) #klasik random modülünde böyle bir özellik bulunmazken

TypeError: Random.randint() takes 3 positional arguments but 4 were given

In [26]:
np.random.randint(0,100,2) #numpy içerisinde özelleşmiş random modülünün içerisinde böyle bir özellik bulunur. 

array([76,  2])

In [29]:
np_array = np.arange(50)
np_multi = np_array.reshape(5,10)
print(np_multi)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]


* sum() fonksiyonu belirtilen aralıktaki değerleri toplama işlemi yapar.

axis = 0 ise satır bazında toplama yapar.``DİKEY TOPLAMA``.Her satırın 0. indexlerini toplar,1.indexlerini toplar,2.indexlerini toplar......

axis = 1 ise sütun bazında toplama yapar.``YATAY TOPLAMA``.Her sütunun 0. indexlerini toplar,1.indexlerini toplar,2.indexlerini toplar......

In [47]:
print(np_multi.sum(axis=0))
#100 = 1.Satırın 0.indexi (0) + 2.Satırın 0.indexi (10) + 3.Satırın 0.indexi (20) + 4.Satırın 0.indexi (30) + 5.Satırın 0.indexi (40) 
#105 = 1.Satırın 1.indexi (1) + 2.Satırın 1.indexi (11) + 3.Satırın 1.indexi  (21) + 4.Satırın 1.indexi  (31) + 5.Satırın 1.indexi (41)
# ...
# ... 
print(100 == np_multi[0][0] + np_multi[1][0] + np_multi[2][0]  + np_multi[3][0]  + np_multi[4][0])
print(105 == np_multi[0][1] + np_multi[1][1] + np_multi[2][1]  + np_multi[3][1]  + np_multi[4][1])


[100 105 110 115 120 125 130 135 140 145]
True
True


In [49]:
print(np_multi.sum(axis=1))
#Yukarıdaki mantığı sütun bazında düşün.

[ 45 145 245 345 445]


# Numpy Array'in Özellikleri 
- ndim : Boyut sayısı(Kaç boyutlu olduğu)
- shape : Boyut bilgisi (...x....) şeklinde
- size : Toplam Eleman sayısı
- dtype : Veri tipi

In [64]:
a = np.random.randint(0,10,10)
# 0 10 aralığında 10 tane eleman üret.
print(a)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)

[5 6 5 8 0 3 0 6 2 0]
1
(10,)
10
int32


``İkisi de aynı şeydir.Aşağıda size= diyerek 0 dan başlayıp 10 a kadar 10 tane eleman üretmesini istiyoruz.``

In [54]:
a = np.random.randint(10, size = 10)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)

1
(10,)
10
int32


<------------------------------------------------------------------------------->

In [67]:
b = np.random.randint(0,10,(3,5)) 
#3,5 = 0 10 aralığında rastgele 5 TANE ELEMAN ÜRET.
# !!VE BUNU 3 KEZ TEKRARLA!!
print(b)
print(b.ndim)
print(b.shape)
print(b.size)
print(b.dtype)

[[7 9 4 3 4]
 [6 8 4 2 0]
 [4 7 1 3 7]]
2
(3, 5)
15
int32


``İkisi de aynı şeydir.``

In [63]:
b = np.random.randint(10, size = (3,5)) #3x5 lik bir array oluştur.
print(b)
print(b.ndim)
print(b.shape)
print(b.size)
print(b.dtype)

[[6 5 2 3 7]
 [5 4 6 2 5]
 [2 0 7 1 2]]
2
(3, 5)
15
int32


# Array Sıralama(Sorting)
* Array sıralama işlemleri yapmak için numpy kütüphanesinde yer alan **sort()** fonksiyonu kullanılır.

In [68]:
v = np.array([2,1,4,3,5])
print(v)
print(np.sort(v))

[2 1 4 3 5]
[1 2 3 4 5]


``Her ikisi de aynı şeydir.``

In [76]:
v = np.array([2,1,4,3,5,77])
v.sort()
print(v)

[ 1  2  3  4  5 77]


-------

* "random.normal" fonksiyonu, Numpy kütüphanesi içinde yer alan bir fonksiyondur. Bu fonksiyon, belirtilen bir ortalamaya (mean) ve standart sapmaya (standard deviation) sahip bir normal dağılım oluşturarak rastgele sayılar üretir.

Fonksiyonun kullanımı aşağıdaki gibidir:


``numpy.random.normal(loc=0.0, scale=1.0, size=None)``
* loc = Normal dağılımın ortalaması.
* scale = standart sapma
* size = sayıların boyutu (3x4) vs.
```
Yani şu demek:
Normal dağılım, bir veri setinin ortalaması etrafında simetrik olarak dağılan bir olasılık dağılımıdır. Ortalama değer, dağılımın merkezini belirler. Standart sapma ise, dağılımın yayılma derecesini gösterir.

"loc" parametresi, normal dağılımın ortalamasını belirler. Örneğin, "loc=0" şeklinde bir parametre verilirse, normal dağılımın ortalaması 0 olacaktır. "loc=5" şeklinde bir parametre verilirse, normal dağılımın ortalaması 5 olacaktır.

"scale" parametresi, normal dağılımın standart sapmasını belirler. Örneğin, "scale=1" şeklinde bir parametre verilirse, normal dağılımın standart sapması 1 olacaktır. "scale=2" şeklinde bir parametre verilirse, normal dağılımın standart sapması 2 olacaktır.

Dolayısıyla, "loc" ve "scale" parametreleri, oluşturulacak normal dağılımın şeklini belirler. Bu parametreler, normal dağılımın merkezini ve yayılma derecesini ayarlamak için kullanılır.

```


In [4]:
import numpy as np
m = np.random.normal(20,5,(3,3))
print(m)

[[21.9564196   8.81145423 25.4324453 ]
 [26.35033884 24.72491024 14.88772121]
 [13.41402617 23.39471986 20.78772022]]


In [12]:
print(np.sort(m, axis=0)) #Dikey olarak sıralama yaptı.(Satır bazında)

[[13.41402617  8.81145423 14.88772121]
 [21.9564196  23.39471986 20.78772022]
 [26.35033884 24.72491024 25.4324453 ]]


In [11]:
print(np.sort(m, axis=1)) #Yatay olarak sıralama yaptı(Sütun bazında)

[[ 8.81145423 21.9564196  25.4324453 ]
 [14.88772121 24.72491024 26.35033884]
 [13.41402617 20.78772022 23.39471986]]


# Index ile Elemanlara Erişmek
Tıpkı listelerde olduğu gibi index ile elemanlara erişebiliri.
```
[satır indexi][sütun indexi] 
veya
[satır indexi,sütun indexi]
```


In [24]:
a = np.random.randint(10,size = 10)
print(a)

[8 0 3 6 5 6 4 7 8 0]


In [25]:
print(a[0])

8


In [26]:
print(a[-1])

0


In [27]:
a[0] = 100 #Listelerde olduğu gibi veri güncelleme işlemi de yapabiliriz.
print(a)

[100   0   3   6   5   6   4   7   8   0]


In [28]:
x = np.random.randint(10,size = (3,5))
print(x)

[[7 4 6 7 9]
 [3 4 3 5 6]
 [8 1 5 5 5]]


-------

In [29]:
print(x[0][0])
print(x[1][1])
print(x[2][4])

7
4
5


```Her ikisi de aynı sonucu verir.Nasıl yazacağın sana kalmış.ALtttakinin yazımı bir tık daha kolay.```

In [30]:
print(x[0,0])
print(x[1,1])
print(x[2,4])

7
4
5


-------

In [31]:
print(x[1,4])
print(x)

6
[[7 4 6 7 9]
 [3 4 3 5 6]
 [8 1 5 5 5]]


In [33]:
x[1,4] = 100
print(x)

[[  7   4   6   7   9]
 [  3   4   3   5 100]
 [  8   1   5   5   5]]


In [32]:
x[1,4] = 3.14 #Ondalıklı sayı eklediğinde tam kısmı yazıyor.Kesirli kısmı yazmıyor.
print(x)

[[7 4 6 7 9]
 [3 4 3 5 3]
 [8 1 5 5 5]]


# Slicing ile Elemanlara Erişmek (Array Alt Kümesine Erişmek)
Tıpkı listelerde olduğu gibi erişebiliyoruz.

In [34]:
a = np.arange(20,30)
print(a)

[20 21 22 23 24 25 26 27 28 29]


In [35]:
print(a[0:3])

[20 21 22]


In [36]:
print(a[:3])

[20 21 22]


In [40]:
print(a[3:])

[23 24 25 26 27 28 29]


In [41]:
print(a[1::2]) # 1 den başla ikişer atla

[21 23 25 27 29]


In [43]:
print(a[0::2]) #0dan başla ikişer atla

[20 22 24 26 28]


In [44]:
print(a[2::2])

[22 24 26 28]


In [45]:
print(a[1::5])

[21 26]


In [46]:
b = np.random.randint(10,size = (5,5))
print(b)

[[6 8 9 5 8]
 [7 9 5 8 6]
 [7 8 0 6 1]
 [2 3 0 6 0]
 [9 3 4 3 1]]


In [57]:
print(b[:,0]) # tüm satırların sıfırıncı sütunlarındaki elemanları al
#Yani 0.sütunda bulunan tüm satır elemanlarını al:
print(b[0,0])
print(b[1,0])
print(b[2,0])
print(b[3,0])
print(b[4,0])

[6 7 7 2 9]
6
7
7
2
9


In [50]:
print(b[:,1]) # tüm satırların birinci sütunlarındaki elemanları al 

[8 9 8 3 3]


In [56]:
print(b[0,:]) # tüm sütunların sıfırıncı satırlarındaki elemanları al
#Yani 0.sütunda bulunan tüm satır elemanlarını al:
print(b[0,0])
print(b[0,1])
print(b[0,2])
print(b[0,3])
print(b[0,4])

[6 8 9 5 8]
6
8
9
5
8


In [59]:
print(b)

[[6 8 9 5 8]
 [7 9 5 8 6]
 [7 8 0 6 1]
 [2 3 0 6 0]
 [9 3 4 3 1]]


In [58]:
print(b[1,:]) # tüm sütunların birinci satırlarındaki elemanları al

[7 9 5 8 6]


In [60]:
print(b[0:2,0:3]) # 0 ve 1. satırların 0,1,2. sütunlarındaki elemanları al

[[6 8 9]
 [7 9 5]]


In [64]:
print(b[::2,::2]) # 2şer 2şer atla
#Yani:
# b[0,0] b[0,2] b[0,4]
# b[2,0] b[2,2] b[2,4]
# b[4,0] b[4,2] b[4,4]

[[6 9 8]
 [7 0 1]
 [9 4 1]]


# Alt Küme Üzerinde İşlem Yapmak

In [66]:
print(b)

[[6 8 9 5 8]
 [7 9 5 8 6]
 [7 8 0 6 1]
 [2 3 0 6 0]
 [9 3 4 3 1]]


In [65]:
alt_b = b[0:3, 0:2]
print(alt_b)

[[6 8]
 [7 9]
 [7 8]]


In [67]:
alt_b[0,0] = 100
alt_b[1,1] = 200
print(alt_b)

[[100   8]
 [  7 200]
 [  7   8]]


In [68]:
print(b)

[[100   8   9   5   8]
 [  7 200   5   8   6]
 [  7   8   0   6   1]
 [  2   3   0   6   0]
 [  9   3   4   3   1]]


# Fancy Index
- Bir liste içine bir arrayden istediğimiz indislerini koyarak o indislerdeki verileri alabiliriz.Toplu getirme işlemi yapar.

In [69]:
v = np.arange(0, 30, 3) # 0 dan 30'a üçer üçer atlayarak git.
print(v)


[ 0  3  6  9 12 15 18 21 24 27]


In [70]:
getir = [1, 3, 5]
print(v[getir])

[ 3  9 15]


``Bu işlemi altta olduğu gibi uzun uzadıya da yapabilirdik.Yukarıdaki kısa,aşağıdaki uzun yol.``

In [76]:
print([v[1] ,v[3], v[5]])

[3, 9, 15]


    veya

In [74]:
liste = [v[1], v[3], v[5]]
print(liste)

[3, 9, 15]


In [78]:
m = np.arange(9).reshape(3, 3)
print(m)
satir = np.array([0, 1])
sutun = np.array([1, 2])
print("<----------->")
print(m[satir, sutun])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
<----------->
[1 5]


In [91]:
print(m[1, [0]]) #1.satırın 0.indexindeki eleman

[3]


In [92]:
print(m[1, [0,1]]) #1.satırın 0. ve 1.indexindeki eleman

[3 4]


In [94]:
print(m[2, [1,2]]) #2.satırın 1. ve 2.indexindeki eleman

[7 8]


In [95]:
print(m[0:, [1, 2]]) #0 dahil olmak üzere ondan sonraki tüm satırlarda 1.ve 2.indexlerdeki sütun elemanları

[[1 2]
 [4 5]
 [7 8]]


# Koşullu Eleman İşlemleri

In [100]:
v = np.array([1, 2, 3, 4, 5,16])
print(v > 3)

[False False False  True  True  True]


In [104]:
v[1]

2

In [101]:
print(v[v > 3]) #3den büyük olanları(4,5,6. indisler.) bul ve sonuçları v[sonucların indisleri] içine yaz.
# v[4] , v[5] , v[6]
#Bu şekilde yaptık çünkü yukarıda boolean(True or False) değer döndürürken burada değerin kendisini döndürür.

[ 4  5 16]


In [105]:
print(v[v < 3])

[1 2]


In [106]:
print(v[v >= 3])

[ 3  4  5 16]


In [107]:
print(v[v <= 3])

[1 2 3]


In [109]:
print(v!=3)
#Görüldüğü gibi array içerisindeki değerleri değil sonuçların True Falseliğine bakar.
#Örneğin aşağıda olduğu gibi direkt 2.indexi False döndürerek onu sonuca almaz.
#Yani 16 değerini : v[16] olarak değil v[5] (5.index True DÖndüğü için) = 16 olarak döndürdü.

[ True  True False  True  True  True]


In [108]:
print(v[v != 3])

[ 1  2  4  5 16]


In [111]:
print(v == 16)

[False False False False False  True]


In [117]:
print(v[v == 16])


[16]


In [118]:
print(v[v == 16]) == print(v[5])
#Görüldüğü gibi TRUE değer döndürdü.

[16]
16


True

Aksi olsaydı:

In [119]:
(v[16]) == (v[5])
#Bu işleme de TRUE döndürürdü.16 index yok ki getiremem diyor.

IndexError: index 16 is out of bounds for axis 0 with size 6

# Matematiksel İşlemler

In [120]:
print(v)

[ 1  2  3  4  5 16]


In [121]:
print(v * 2)

[ 2  4  6  8 10 32]


In [122]:
print(v + 2)

[ 3  4  5  6  7 18]


In [123]:
print(v * 5 / 10)

[0.5 1.  1.5 2.  2.5 8. ]


In [124]:
print(v ** 2)

[  1   4   9  16  25 256]


In [126]:
print(v)

[ 1  2  3  4  5 16]


In [125]:
print(np.subtract(v, 2)) # .subtract() fonksiyonu vektörlerde çıkarma işlemi yapar.
# v deki elemanların hepsinden 2 çıkardık.

[-1  0  1  2  3 14]


In [127]:
print(np.add(v, 2)) # .add() fonksiyonu vektörlerde toplama işlemi yapar.
#Hepsine 2 ekledik.

[ 3  4  5  6  7 18]


In [128]:
print(np.multiply(v, 2)) # .multiply() fonksiyonu vektörlerde çarpma işlemi yapar.

[ 2  4  6  8 10 32]


In [129]:
print(np.divide(v, 2)) #.divide()  fonksiyonu vektörlerde bölme işlemi yapar.

[0.5 1.  1.5 2.  2.5 8. ]


In [130]:
print(np.power(v, 2)) # .power() fonksiyonu vektörlerde üs alma işlemi yapar.

[  1   4   9  16  25 256]


In [131]:
print(np.mod(v, 2)) # .mod() fonksiyonu vektörlerde mod alma işlemi yapar.

[1 0 1 0 1 0]


In [132]:
print(np.absolute(v)) # .absolute() fonksiyonu vektörlerde mutlak değer alma işlemi yapar.

[ 1  2  3  4  5 16]


In [133]:
print(np.sin(360)) # .sin() fonksiyonu vektörlerde sinüs alma işlemi yapar.

0.9589157234143065


In [134]:
np.cos(360) # .cos() fonksiyonu vektörlerde kosinüs alma işlemi yapar.

-0.2836910914865273

In [135]:
print(np.log(10)) # .log() fonksiyonu vektörlerde logaritma alma işlemi yapar.

2.302585092994046
