# Numpy
- Numpy sayısal işlemleri hızlı yapmak için C dili ile yazılmış bir Python kütüphanesidir.
- Veri analizinde kullanılır.
- Bilgisayar kurmak için ```pip insall numpy``` komutu ile kurulabilir.
- Bilimsel hesaplamalar için kullanılır.
- Arraylar(diziler) / çok boyutlu arrayler(matrisler) üzerinde yüksek performanslı işlemler yapılabilir.
- Temelleri 1995 yılında atıldı. Ama nihai olarak 2005 yılında Travis Oliphant tarafından hayata geçmiştir.
- Listelere benzerdir. Fakat verimli veri saklama ve vektör işlemleri için Numpy kullanılır.

In [ ]:
pip install numpy

### Dizi(array) ve liste farkları:

Python'da, dizi (array) ve liste (list) her ikisi de birden fazla öğenin saklanması için kullanılan veri yapılarıdır. Ancak, diziler ve listeler arasında bazı farklılıklar vardır:

1.) Veri tipi: Diziler, homojen bir veri tipine sahip öğeleri tutmak için kullanılırken, listeler heterojen veri tipleri için kullanılabilir. Yani, bir dizi yalnızca tamsayıları veya yalnızca ondalık sayıları tutabilirken, bir listede hem tamsayılar hem de ondalık sayılar yer alabilir.

2.) Bellek yönetimi: Diziler bellek yönetimi açısından daha verimlidir. Listeler, elemanları farklı bellek adreslerinde saklar ve bir listenin her elemanı, bellekte farklı bir konumda depolanırken, diziler bellekte ardışık bir alanda saklanır.

3.) Boyut: Diziler tek boyutlu veya çok boyutlu olabilirken, listeler sadece tek boyutludur.

4.) İşlemler: Diziler, matematiksel işlemleri yapmak için uygun bir şekilde tasarlanmıştır. Bu nedenle, NumPy ve diğer kütüphaneler dizileri kullanarak veri işleme işlemlerini gerçekleştirmek için kullanılır. Listeler ise genellikle öğelerin eklenmesi, çıkarılması, sıralanması, aranması gibi işlemler için kullanılır.

Özetle, diziler ve listeler arasındaki temel fark, veri tipi, bellek yönetimi, boyut ve işlemlerdir. Diziler homojen veriler için daha uygundurken, listeler heterojen veriler için daha uygundur ve her ikisi de farklı veri işleme ihtiyaçlarına yöneliktir.

In [13]:
my_list = ([1, 2, 3], [4, 5, 6])
print(my_list)

([1, 2, 3], [4, 5, 6])


In [12]:

my_array = np.array([[1, 2, 3], [4, 5, 6]])
print(my_array)


[[1 2 3]
 [4 5 6]]


In [4]:
# bir dizi (array) oluşturma
my_array = np.array([1, 2, 3, 4, 5])
print("Dizi: ", my_array)
print("Dizinin boyutu: ", my_array.shape)
print("Dizinin veri tipi: ", my_array.dtype)

# bir liste (list) oluşturma
my_list = [1, "iki", 3.0, "dört", 5]
print("Liste: ", my_list)
print("Listenin boyutu: ", len(my_list))

# dizi ile matematiksel işlem yapma
my_array_squared = my_array ** 2
print("Dizinin karesi: ", my_array_squared)

# listenin öğelerini ekleme ve silme
my_list.append("altı")
print("Listeye 'altı' eklendi: ", my_list)

my_list.remove("iki")
print("Listeden 'iki' çıkarıldı: ", my_list)


Dizi:  [1 2 3 4 5]
Dizinin boyutu:  (5,)
Dizinin veri tipi:  int32
Liste:  [1, 'iki', 3.0, 'dört', 5]
Listenin boyutu:  5
Dizinin karesi:  [ 1  4  9 16 25]
Listeye 'altı' eklendi:  [1, 'iki', 3.0, 'dört', 5, 'altı']
Listeden 'iki' çıkarıldı:  [1, 3.0, 'dört', 5, 'altı']


Bu örnekte, bir dizi ve bir liste oluşturduk. Dizinin elemanları tam sayı, liste ise hem tam sayı hem de string ifadeler içeriyor. Dizinin boyutunu shape özelliği ile kontrol ederken, listenin boyutunu len fonksiyonu ile kontrol ettik. Dizi için matematiksel bir işlem yaparken, listenin elemanlarını ekleyip ve çıkardık. Bu örnek, dizilerin matematiksel işlemler için daha uygun olduğunu ve listelerin veri ekleme ve çıkarma işlemleri için daha uygun olduğunu göstermektedir.

----

## Array ve matris farkı nedir?

Python'da bir dizi, tek boyutlu bir veri yapısıdır. Bu dizi, aynı veri türünden elemanları içerir ve indeksleme yöntemi kullanılarak erişilebilir.

Bir matris ise, iki boyutlu bir veri yapısıdır ve satır ve sütunlardan oluşur. Matrisler, aynı veri türünden elemanları içerir ve bir öğenin konumu, satır ve sütun indeksleri kullanılarak belirlenir. Matrisler, bir dizi gibi düzgün bir şekilde düzenlenmiş bir veri yapısıdır ve matematiksel işlemler için kullanılabilirler.

Python'da, bir dizi oluşturmak için array modülünü kullanabilirsiniz, ancak bu sadece tek boyutlu bir dizi oluşturur. Matrisler için ise, numpy modülü kullanılabilir. numpy modülü, matrislerin yanı sıra çok boyutlu diziler için de kullanılabilir.

Python'da, bir dizi (array) veya matris (matrix) kullanarak çok boyutlu verileri temsil edebilirsiniz.

Bir dizi, aynı türdeki öğelerin sıralı bir koleksiyonudur. Örneğin, bir dizi içinde tam sayılar, ondalık sayılar veya karakterler gibi veri tipleri yer alabilir. NumPy gibi kütüphaneler, Python'da dizileri işlemek için kullanılabilir.

Bir matris, iki boyutlu bir dizi olarak düşünülebilir ve bu nedenle aynı türdeki öğelerin düzenli bir şekilde yer aldığı bir koleksiyondur. Bir matris, satırlar ve sütunlar olmak üzere iki boyutlu bir indekslemeye sahiptir ve bu şekilde elemanlarına erişilebilir. Örneğin, bir matris içinde tamsayılar, ondalık sayılar veya karmaşık sayılar gibi veri tipleri yer alabilir. NumPy kütüphanesi, Python'da matrisleri işlemek için kullanılabilir.

Özetle, dizi tek boyutlu bir veri koleksiyonunu, matris ise iki boyutlu bir veri koleksiyonunu ifade eder.

Bir örnek ile açıklamak gerekirse:

In [23]:
import numpy as np

# bir array (dizi) oluşturma
my_array = np.array([1, 2, 3, 4, 5])
print("Array: ", my_array)
print("Array boyutu: ", my_array.shape)

# bir matris (matrix) oluşturma
my_matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Matris: ")
print(my_matrix)
print("Matris boyutu: ", my_matrix.shape)


Array:  [1 2 3 4 5]
Array boyutu:  (5,)
Matris: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Matris boyutu:  (3, 3)


## Matrisleri İsimlendirme


![Image](https://cdn.programiz.com/sites/tutorial2program/files/matrix.jpg)

![Image](https://www.guru99.com/images/2/062620_0641_PythonMatri1.png)

``
*Önce row(satır) sayısı,sonra column(sütun)sayısı yazılır.*
``

Python'da, birden fazla boyutu olan dizilere (arrays) "çok boyutlu diziler" denir. NumPy kütüphanesi, Python'da çok boyutlu dizileri kullanmak için yaygın bir araçtır.

Örneğin, 2x3 boyutlu bir dizi(array) şu şekilde oluşturulabilir:

In [3]:

my_array = np.array([[1, 2, 3], [4, 5, 6]])
print(my_array)


[[1 2 3]
 [4 5 6]]


In [11]:
my_list = ([1, 2, 3], [4, 5, 6])
print(my_list)

([1, 2, 3], [4, 5, 6])


Bu örnekte, np.array() fonksiyonu ile bir 2x3 ``(Önce row(satır),daha sonra column(sütun)sayısı yazılır.)`` boyutlu bir dizi oluşturuldu. İç içe iki liste kullanarak her satırın elemanlarını belirttik. Dizinin her bir öğesi, [satır, sütun] şeklinde bir indeksleme kullanılarak erişilebilir. Örneğin, my_array[0, 1] ifadesi, ilk satırın ikinci sütunundaki öğeye erişecektir ve 2 sonucunu verecektir.

# Neden Numpy?

In [18]:
#KLasik Yöntem
a = [1,2,3,4]
b = [2,3,4,5]
c = 0
ab = []
for i in range(0, len(a)):
    print(i,". dolaşma")
    c+=1
    ab.append(a[i] * b[i])
print(c,"kez dolaştım.")
print(ab)

0 . dolaşma
1 . dolaşma
2 . dolaşma
3 . dolaşma
4 kez dolaştım.
[2, 6, 12, 20]


In [4]:
#Numpy Metodu
import numpy as np #np olarak çağırabileyim.Kısaltma olarak np koydum.
a = np.array([1,2,3,4]) #Numpy'da array oluştururken np.array yöntemi kullanılır.
print(a)
b = np.array([2,3,4,5])
print(b)
print(a*b)

[1 2 3 4]
[2 3 4 5]
[ 2  6 12 20]


## Numpy Fonksiyonları

.reshape() : arraylerin veya matrislerin boyutunu değiştirir.

In [25]:
x = np.array([1,2,3,4,5,6,7,8,9]) # 1 boyutlu bir array'dir. Boyutu 9'dur, yani içinde dokuz eleman bulunur.
#x bir sütun matrisi (9x1) değil, tek boyutlu bir dizi veya vektördür (1x9)(önce satır sonra sütun)
# Ancak biz 1x9 demek yerine böyle arraylere 9'a 0'lık(9, ) array deriz.
print(x)
multi = x.reshape(3,3) #multi ise 2 boyutlu bir matristir.(çok boyutlu bir arraydir.)
#3x3'lük(3,3) bir matristir.(3satır,3 sütun)
print(multi)
#Aslında biz burda bir arrayı matrise çevirdik.

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


.shape : arraylerin veya matrislerin boyutlarını verir.    

In [29]:
print(x.shape)

(9,)


In [27]:
print(multi.shape)

(3, 3)


ndim : Arraylerin veya Matrislerin  boyut sayısını verir.  

In [20]:
print(x.ndim) #1 boyutludur.

1


In [21]:
print(multi.ndim) #2 boyutludur.
# 2 boyutlu matris
#       veya
# 2 boyutlu array
# diyebiliriz.Her ikisi de aynı anlama gelir.

2


# Birleştirme (Concatenation)
- .concatenate() fonksiyonu ile birleştirme yapabiliriz.Örneğin elimizde 2 tane numpy arrayi olsun,biz bu 2 arrayi birleştirmek için kullanırız.

In [33]:
x = np.array([1,2,3,4,5])
print(x)
y = np.array([6,7,8,9,10])
print(y) # Bunu ayrık yazmasının sebebi içinde 2 basamaklı bir sayı bulunmasıdır.
print(np.concatenate([x, y]))

[1 2 3 4 5]
[ 6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]


---

- Bunu ayrık yazmasının sebebi içinde 2 basamaklı bir sayı bulunmasıdır.

In [36]:
y = np.array([6,7,8,9])
print(y)
y = np.array([6,7,8,9,10])
print(y)

[6 7 8 9]
[ 6  7  8  9 10]
[11 12 13 14]


-------

-----

In [60]:
z = np.array([11,12,13,14,15])
print(z) #Bir boyutlu array.

[11 12 13 14 15]


In [61]:
z = np.array([[11,12,13,14,15]])
print(z) #İki boyutlu array.

[[11 12 13 14 15]]


In [63]:
a = np.array([1,2,3], [4,5,6])
print(a)
#Yani böyle yaparsan hata alırsın.Sen bana 2 boyutlu bir şey verdin
#Ama tek köşeli parantez([]) kullanarak bunun tek boyutlu olduğunu söylüyorsun der.

TypeError: Field elements must be 2- or 3-tuples, got '4'

In [24]:
a = np.array([[1,2,3], [4,5,6]])
print(a) #Sorunu iki tane [[]] kullanarak çözdük.

[[1 2 3]
 [4 5 6]]


-----

In [2]:
import numpy as np

In [58]:
z = np.array([11,12,13,14,15])
print(np.concatenate([x, y, z]))

[ 1  2  3  4  5 11 12 13 14 11 12 13 14 15]


In [3]:
a = np.array([[1,2,3], [4,5,6]])
print(a)


[[1 2 3]
 [4 5 6]]


In [4]:
b = np.array([[7,8,9]])
print(b)

[[7 8 9]]


In [5]:
print(np.concatenate([a,b])) 


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
print(np.concatenate([a,a])) 

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]


axis = 0 ise satır bazında birleştirme yapar.

axis = 1 ise sütun bazında birleştirme yapar.

In [21]:
c = np.array([[7,8,9], [10,11,12]])
print(c)

[[ 7  8  9]
 [10 11 12]]


In [10]:
print(np.concatenate([a,c], axis=0))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [17]:
print(np.concatenate([a,a], axis=0))

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]


In [19]:
print(a)
print("-----------")
print(c)

[[1 2 3]
 [4 5 6]]
-----------
[[ 7  8  9]
 [10 11 12]]


In [18]:
print(np.concatenate([a,c], axis=1))

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [12]:
print(np.concatenate([a,a], axis=1))

[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


# Array Ayırma (Splitting)

## .split() fonksiyonu ile array ayırma yapabiliriz.

In [55]:
m = np.array([1,2,3,4,5,6,7,8,9])
print(m)
print(m[0])
print(m[1])
print(m[2])
print(m[3])
print(m[4])
print(m[5])
print(m[6])
print(m[7])
print(m[8])

[1 2 3 4 5 6 7 8 9]
1
2
3
4
5
6
7
8
9


In [50]:
print(np.split(m, [3,5])) #3.elemandan(indexten) 5.elemana(indexe) kadar.(5 dahil değil.)

[array([1, 2, 3]), array([4, 5]), array([6, 7, 8, 9])]


In [23]:
n = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
print(np.split(n, [3,5]))

[array([1, 2, 3]), array([4, 5]), array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15])]


In [26]:
print(np.split(n, [1,5]))

[array([1]), array([2, 3, 4, 5]), array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15])]


In [30]:
print(np.split(n, [10,12]))

[array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]), array([11, 12]), array([13, 14, 15])]


In [56]:
a,b,c = np.split(m, [3,5])
print(a,b,c)
print(a)
print(b)
print(c)

[1 2 3] [4 5] [6 7 8 9]
[1 2 3]
[4 5]
[6 7 8 9]


In [31]:
a,b,c = np.split(n, [10,12])
print(a,b,c)
print(a)
print(b)
print(c)

[ 1  2  3  4  5  6  7  8  9 10] [11 12] [13 14 15]
[ 1  2  3  4  5  6  7  8  9 10]
[11 12]
[13 14 15]


## arange() fonksiyonu  belirli bir aralıktaki sayıları içeren bir dizi oluşturmak için kullanılan bir fonksiyondur.
* Fonksiyonun genel kullanımı şu şekildedir:
* ``numpy.arange([start,] stop[, step,][, dtype=None])``
* start (opsiyonel): Diziye dahil edilecek ilk sayı. Varsayılan olarak 0'dır.
* stop: Diziye dahil edilmeyecek son sayı.
* step (opsiyonel): Sayılar arasındaki artışın miktarı. Varsayılan olarak 1'dir.
* dtype (opsiyonel): Oluşturulan dizinin veri tipi. Varsayılan olarak None olarak ayarlanır, ancak belirtilirse, oluşturulan dizi bu veri türünde olacaktır.
Örnek kullanımı:



In [32]:
# 0'dan 10'a kadar sayılar içeren bir dizi oluştur
arr1 = np.arange(10)
print(arr1)   # [0 1 2 3 4 5 6 7 8 9]
# 1'den 9'a kadar sayılar içeren bir dizi oluştur (1 dahil, 10 hariç)
arr2 = np.arange(1, 10)
print(arr2)   # [1 2 3 4 5 6 7 8 9]
# 0'dan 1'e kadar 0.1 artarak sayılar içeren bir dizi oluştur
arr3 = np.arange(0, 1, 0.1)
print(arr3)   # [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


[0 1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


Biz bu işlemi listelerde:

In [34]:
liste = []
for i in range(0,10):
    liste.append(i)
print(liste)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


şeklinde yapıyorduk.

In [46]:
n = np.arange(16)
print(n)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [8]:
n = np.arange(16).reshape(4,4) #4x4 olacak şekilde boyutunu değiştir.
print(n)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [48]:
print(n[0]) #0.satırı yazdır.
print(n[1]) #1.satırı yazdır.
print(n[2]) #2.satırı yazdır.
print(n[3]) #3.satırı yazdır.


[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]


In [49]:
print(n[0][1]) #0.satırın 1.indexini yazdır.
print(n[1][2]) #1.satırın 2.indexini yazdır.
print(n[2][3]) #2.satırın 3.indexini yazdır.
print(n[3][3]) #3.satırın 3.indexini yazdır.

1
6
11
15


In [9]:
np.split(n, [1]) #(n, [0,1]) aynı şey. 

[array([[0, 1, 2, 3]]),
 array([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

## vsplit() bir NumPy dizisini yatay olarak(satır bazında) bölerek birden fazla alt dizilere ayırır. Dizi, satırlar boyunca bölünür.
* Fonksiyonun kullanımı şu şekildedir:
* ``numpy.vsplit(array, indices_or_sections)``
* array: Bölünecek NumPy dizisidir,
* indices_or_sections: Dizideki satır sayısını kaç parçaya ayırayım(kaç satıra çevireyim ?)(alt dizilerin sayısı veya bölmelerin indeksleridir.)
- Örnek olarak, 6 satır ve 4 sütundan oluşan bir NumPy dizisi alalım:

In [48]:
arr = np.arange(24).reshape((6, 4))
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


Bu diziyi, 3 parçaya ayırmak için numpy.vsplit() kullanabiliriz:

In [78]:
pieces = np.vsplit(arr, 3)
print(pieces)

[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]]), array([[16, 17, 18, 19],
       [20, 21, 22, 23]])]


Burada, pieces değişkeni, 3 adet NumPy dizi objesi içeren bir listeye atanmıştır. Bu objeler, orijinal dizinin satırlarının yatay olarak eşit bölünmüş halidir.

<img src="Vsplit.jpg" alt="görsel yorumu"> 

* BİZ 3 PARÇAYA BÖLMESİNİ SÖYLEMİŞTİK.O HALDE:
* ``*6 SATIRI 3 E BÖLECEĞİM.6/3=2 VE HER PARÇA 2 SATIRDAN OLUŞACAK.*``
* ``1.SATIR = 1.PARÇA(2 SATIRDAN OLUŞUYOR.)``
* ``2.SATIR = 2.PARÇA(2 SATIRDAN OLUŞUYOR.)``
* ``3.SATIR = 3.PARÇA(2 SATIRDAN OLUŞUYOR.)``
Gibi düşünebilirsin.

In [50]:
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [62]:
pieces = np.vsplit(arr, 4)
# Hata aldık çünkü 6 satırlık bir dizi 4 satıra tam olarak bölünmez(6/4 = 1.5) 
#Her parça 1.5 satırdan oluşamaz diyor.

ValueError: array split does not result in an equal division

In [90]:
pieces = np.vsplit(arr, 6) #6 eşit parçaya böldüm ve her parçada 6/6 = 1'den 1 satırdan oluştu.
print(pieces)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]]), array([[12, 13, 14, 15]]), array([[16, 17, 18, 19]]), array([[20, 21, 22, 23]])]


In [63]:
n = np.arange(16).reshape(4,4)
print(n)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [80]:
np.vsplit(n, [2]) #4 Satırlık arrayi 2 eşit parçaya böl.
#O Halde 4/2 = 2 den her parça da 2 satırdan oluşsun. 

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

## hsplit() fonksiyonu, bir NumPy dizisini dikey olarak bölerek birden fazla alt dizilere ayırır. Dizi, sütunlar boyunca bölünür.
* numpy.hsplit() fonksiyonu aşağıdaki şekilde kullanılır:
* ``numpy.hsplit(array, indices_or_sections)``
* array :  bölünecek NumPy dizisidir, 
* indices_or_sections :Dizideki sütun sayısını kaç parçaya ayırayım(kaç sütuna çevireyim ?)(alt dizilerin sayısı veya bölmelerin indeksleridir.)

Örnek olarak, 6 satır ve 4 sütundan oluşan bir NumPy dizisi alalım:

In [92]:
arr = np.arange(24).reshape((6, 4))
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


Bu diziyi, 2 parçaya ayırmak için numpy.hsplit() kullanabiliriz:

In [99]:
pieces = np.hsplit(arr, 2)
print(pieces)

[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13],
       [16, 17],
       [20, 21]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15],
       [18, 19],
       [22, 23]])]


<img src="Hsplit.jpg" alt="görsel yorumu"> 

*Toplamda 2 PARÇAYA böl.
* ``1.SÜTUN = 1.PARÇA``
* ``2.SÜTUN = 2.PARÇA``
* Gibi düşünebilirsin.

In [100]:
pieces = np.hsplit(arr, 4)
print(pieces)

[array([[ 0],
       [ 4],
       [ 8],
       [12],
       [16],
       [20]]), array([[ 1],
       [ 5],
       [ 9],
       [13],
       [17],
       [21]]), array([[ 2],
       [ 6],
       [10],
       [14],
       [18],
       [22]]), array([[ 3],
       [ 7],
       [11],
       [15],
       [19],
       [23]])]


<img src="Hsplit 2.jpg" alt="görsel yorumu"> 

In [102]:
n = np.arange(16).reshape(4,4)
print(n)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [105]:
np.hsplit(n, [2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [106]:
a,b = np.hsplit(n, [2])
print(a)
print("<------------->")
print(b)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
<------------->
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
